import Foundation

public struct ReceiptOCRBenchmarkPaths {
    public let receiptsFolder: URL
    public let fixturesRoot: URL
    public let runsRoot: URL

    public init(receiptsFolder: URL, fixturesRoot: URL, runsRoot: URL) {
        self.receiptsFolder = receiptsFolder
        self.fixturesRoot = fixturesRoot
        self.runsRoot = runsRoot
    }
}

public struct ReceiptOCRBenchmarkCase: Identifiable {
    public let id: String
    public let imageURL: URL
    public let fixtureDirectory: URL

    public var expectedURL: URL { fixtureDirectory.appendingPathComponent("expected.json") }
    public var baselineURL: URL { fixtureDirectory.appendingPathComponent("baseline.current.json") }
    public var transcriptURL: URL { fixtureDirectory.appendingPathComponent("transcript.txt") }
}

public enum ReceiptOCRBenchmarkError: Error {
    case unsupportedFileType(URL)
}

public struct ReceiptOCRRunOptions {
    public let runID: String
    public let resumeExistingResults: Bool
    public let continueOnCaseError: Bool
    public let includedCaseIDs: Set<String>?
    public let transcriptFilename: String?

    public init(
        runID: String = "latest",
        resumeExistingResults: Bool = true,
        continueOnCaseError: Bool = true,
        includedCaseIDs: Set<String>? = nil,
        transcriptFilename: String? = nil
    ) {
        self.runID = runID
        self.resumeExistingResults = resumeExistingResults
        self.continueOnCaseError = continueOnCaseError
        self.includedCaseIDs = includedCaseIDs
        self.transcriptFilename = transcriptFilename
    }
}

public final class ReceiptOCRBenchmarkRunner {
    private let fileManager: FileManager
    private let jsonEncoder: JSONEncoder
    private let jsonDecoder: JSONDecoder
    private let fileReadRetryLimit = 12

    public init(fileManager: FileManager = .default) {
        self.fileManager = fileManager
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        jsonEncoder = encoder

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        jsonDecoder = decoder
    }

    public func discoverCases(paths: ReceiptOCRBenchmarkPaths) throws -> [ReceiptOCRBenchmarkCase] {
        let urls = try fileManager.contentsOfDirectory(at: paths.receiptsFolder, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles])
        let allowedExtensions = Set(["jpg", "jpeg", "png", "heic", "heif", "webp"])

        return urls
            .filter { allowedExtensions.contains($0.pathExtension.lowercased()) }
            .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }
            .map { imageURL in
                let id = Self.caseIdentifier(for: imageURL)
                return ReceiptOCRBenchmarkCase(
                    id: id,
                    imageURL: imageURL,
                    fixtureDirectory: paths.fixturesRoot.appendingPathComponent(id, isDirectory: true)
                )
            }
    }

    public func bootstrapExpectedFixtures(using workflow: any ReceiptOCRWorkflowing, paths: ReceiptOCRBenchmarkPaths, overwriteExpected: Bool = false) async throws -> [ReceiptOCRFixtureRecord] {
        let cases = try discoverCases(paths: paths)
        var written: [ReceiptOCRFixtureRecord] = []

        for benchmarkCase in cases {
            let image = try ReceiptImage.load(from: benchmarkCase.imageURL)
            let result = try await workflow.run(image: image, prefetchedTranscriptTask: nil)
            let snapshot = ReceiptOCRBenchmarkSnapshot(from: result)

            try ensureDirectory(benchmarkCase.fixtureDirectory)
            try writeText(snapshot.transcript, to: benchmarkCase.transcriptURL)

            let baseline = ReceiptOCRFixtureRecord(
                caseID: benchmarkCase.id,
                sourceFilename: benchmarkCase.imageURL.lastPathComponent,
                variantID: workflow.variantID,
                capturedAt: Date(),
                reviewStatus: .needsReview,
                notes: "Autogenerated from the current workflow. Review and correct expected.json before using scores.",
                snapshot: snapshot
            )

            try writeJSON(baseline, to: benchmarkCase.baselineURL)
            if overwriteExpected || !fileManager.fileExists(atPath: benchmarkCase.expectedURL.path) {
                try writeJSON(baseline, to: benchmarkCase.expectedURL)
                written.append(baseline)
            }
        }

        return written
    }

    public func runSuite(
        workflows: [any ReceiptOCRWorkflowing],
        paths: ReceiptOCRBenchmarkPaths,
        options: ReceiptOCRRunOptions = .init()
    ) async throws -> [ReceiptOCRBenchmarkRunSummary] {
        let allCases = try discoverCases(paths: paths)
        let cases: [ReceiptOCRBenchmarkCase]
        if let includedCaseIDs = options.includedCaseIDs, !includedCaseIDs.isEmpty {
            cases = allCases.filter { includedCaseIDs.contains($0.id) }
        } else {
            cases = allCases
        }
        let runDirectory = paths.runsRoot.appendingPathComponent(options.runID, isDirectory: true)
        try ensureDirectory(runDirectory)

        var summaries: [ReceiptOCRBenchmarkRunSummary] = []
        for workflow in workflows {
            let variantDirectory = runDirectory.appendingPathComponent(workflow.variantID, isDirectory: true)
            try ensureDirectory(variantDirectory)
            var caseResults: [ReceiptOCRBenchmarkCaseResult] = []

            for benchmarkCase in cases {
                let outputURL = variantDirectory.appendingPathComponent("\(benchmarkCase.id).json")

                if options.resumeExistingResults,
                   let existing = try loadCaseResultIfPresent(at: outputURL) {
                    caseResults.append(existing)
                    continue
                }

                do {
                    let image = try ReceiptImage.load(from: benchmarkCase.imageURL)
                    let prefetchedTranscriptTask = try makePrefetchedTranscriptTask(
                        for: benchmarkCase,
                        transcriptFilename: options.transcriptFilename
                    )
                    let result = try await workflow.run(image: image, prefetchedTranscriptTask: prefetchedTranscriptTask)
                    let snapshot = ReceiptOCRBenchmarkSnapshot(from: result)
                    let expected = try loadExpectedRecordIfPresent(at: benchmarkCase.expectedURL)
                    let score = expected.map { Self.score(snapshot: snapshot, expected: $0.snapshot) }

                    let caseResult = ReceiptOCRBenchmarkCaseResult(
                        caseID: benchmarkCase.id,
                        sourceFilename: benchmarkCase.imageURL.lastPathComponent,
                        variantID: workflow.variantID,
                        capturedAt: Date(),
                        score: score,
                        snapshot: snapshot,
                        expectedReviewStatus: expected?.reviewStatus,
                        errorDescription: nil
                    )

                    try writeJSON(caseResult, to: outputURL)
                    caseResults.append(caseResult)
                } catch {
                    if !options.continueOnCaseError {
                        throw error
                    }

                    fputs("[ocrbench] Case failed: \(benchmarkCase.id): \(error)\n", stderr)
                    let expectedReviewStatus = (try? loadExpectedRecordIfPresent(at: benchmarkCase.expectedURL))??.reviewStatus
                    let failedResult = ReceiptOCRBenchmarkCaseResult(
                        caseID: benchmarkCase.id,
                        sourceFilename: benchmarkCase.imageURL.lastPathComponent,
                        variantID: workflow.variantID,
                        capturedAt: Date(),
                        score: nil,
                        snapshot: .empty,
                        expectedReviewStatus: expectedReviewStatus,
                        errorDescription: String(describing: error)
                    )
                    try writeJSON(failedResult, to: outputURL)
                    caseResults.append(failedResult)
                }
            }

            let summary = Self.summarize(results: caseResults, variantID: workflow.variantID)
            try writeJSON(summary, to: variantDirectory.appendingPathComponent("summary.json"))
            summaries.append(summary)
        }

        try writeJSON(summaries, to: runDirectory.appendingPathComponent("suite-summary.json"))
        return summaries
    }

    private func makePrefetchedTranscriptTask(
        for benchmarkCase: ReceiptOCRBenchmarkCase,
        transcriptFilename: String?
    ) throws -> Task<String, Error>? {
        guard let transcriptFilename else { return nil }
        let transcriptURL = benchmarkCase.fixtureDirectory.appendingPathComponent(transcriptFilename)
        let transcript = try String(contentsOf: transcriptURL, encoding: .utf8)
        return Task { transcript }
    }

    private func loadExpectedRecordIfPresent(at url: URL) throws -> ReceiptOCRFixtureRecord? {
        guard fileManager.fileExists(atPath: url.path) else { return nil }
        return try jsonDecoder.decode(ReceiptOCRFixtureRecord.self, from: readDataWithRetry(from: url))
    }

    private func loadCaseResultIfPresent(at url: URL) throws -> ReceiptOCRBenchmarkCaseResult? {
        guard fileManager.fileExists(atPath: url.path) else { return nil }
        return try jsonDecoder.decode(ReceiptOCRBenchmarkCaseResult.self, from: readDataWithRetry(from: url))
    }

    private func ensureDirectory(_ url: URL) throws {
        try fileManager.createDirectory(at: url, withIntermediateDirectories: true, attributes: nil)
    }

    private func writeJSON<T: Encodable>(_ value: T, to url: URL) throws {
        try jsonEncoder.encode(value).write(to: url, options: .atomic)
    }

    private func writeText(_ text: String, to url: URL) throws {
        try text.write(to: url, atomically: true, encoding: .utf8)
    }

    private func readDataWithRetry(from url: URL) throws -> Data {
        var attempt = 0
        while true {
            attempt += 1
            do {
                return try Data(contentsOf: url)
            } catch {
                guard attempt < fileReadRetryLimit else { throw error }
                Thread.sleep(forTimeInterval: min(Double(attempt), 5.0))
            }
        }
    }

    private static func caseIdentifier(for url: URL) -> String {
        let stem = url.deletingPathExtension().lastPathComponent.lowercased()
        let raw = String(stem.unicodeScalars.map {
            CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_")).contains($0) ? Character($0) : "-"
        })
        let collapsed = raw.replacingOccurrences(of: "--+", with: "-", options: .regularExpression)
        return collapsed.trimmingCharacters(in: CharacterSet(charactersIn: "-"))
    }

    private static func score(snapshot actual: ReceiptOCRBenchmarkSnapshot, expected: ReceiptOCRBenchmarkSnapshot) -> ReceiptOCRBenchmarkScore {
        let merchant = labelSimilarity(actual.phase1.merchant, expected.phase1.merchant)
        let total = numericSimilarity(actual.phase1.total_cents, expected.phase1.total_cents)
        let breakdown = average(of: [
            numericSimilarity(actual.phase2.subtotal_cents, expected.phase2.subtotal_cents),
            numericSimilarity(actual.phase2.tax_cents, expected.phase2.tax_cents),
            numericSimilarity(actual.phase2.tip_cents, expected.phase2.tip_cents),
            numericSimilarity(actual.phase2.fees_cents, expected.phase2.fees_cents),
            numericSimilarity(actual.phase2.discount_cents, expected.phase2.discount_cents)
        ])
        let itemValues = unorderedItemValueSimilarity(actual.phase2.items, expected.phase2.items)
        let lineItemValues = unorderedLineItemValueSimilarity(actual.lineItems, expected.lineItems)
        let expectedTotal: Int? = expected.phase1.total_cents ?? computedTotal(for: expected)
        let actualComputedTotal = computedTotal(for: actual)
        let reconciliationDifference = expectedTotal.map { actualComputedTotal - $0 }
        let reconciliationPass = reconciliationDifference == 0
        let reconciliation = reconciliationDifference.map { $0 == 0 ? 1.0 : 0.0 } ?? 0.0
        let overall = average(weightedValues: [
            (reconciliation, 0.55),
            (total, 0.15),
            (breakdown, 0.10),
            (itemValues, 0.15),
            (lineItemValues, 0.05)
        ])

        return ReceiptOCRBenchmarkScore(
            passesTotalReconciliation: reconciliationPass,
            expectedTotalCents: expectedTotal,
            actualComputedTotalCents: actualComputedTotal,
            reconciliationDifferenceCents: reconciliationDifference,
            reconciliation: reconciliation,
            overall: overall,
            merchant: merchant,
            total: total,
            breakdown: breakdown,
            itemValues: itemValues,
            lineItemValues: lineItemValues
        )
    }

    private static func summarize(results: [ReceiptOCRBenchmarkCaseResult], variantID: String) -> ReceiptOCRBenchmarkRunSummary {
        let transcriptSeconds = results.map(\.snapshot.timings.transcriptSeconds)
        let phase1Seconds = results.map(\.snapshot.timings.phase1Seconds)
        let phase2Seconds = results.compactMap(\.snapshot.timings.phase2Seconds)
        let totalWorkflowSeconds = results.compactMap(\.snapshot.timings.totalWorkflowSeconds)
        let overallScores = results.compactMap { $0.score?.overall }
        let reconciliationScores = results.compactMap { $0.score?.reconciliation }
        let passCount = results.compactMap(\.score).filter(\.passesTotalReconciliation).count
        let failedCaseCount = results.filter { $0.errorDescription != nil }.count

        return ReceiptOCRBenchmarkRunSummary(
            variantID: variantID,
            caseCount: results.count,
            scoredCaseCount: overallScores.count,
            passCount: passCount,
            failedCaseCount: failedCaseCount,
            averageOverallScore: overallScores.isEmpty ? nil : average(of: overallScores),
            averageReconciliationScore: reconciliationScores.isEmpty ? nil : average(of: reconciliationScores),
            averageTranscriptSeconds: average(of: transcriptSeconds),
            averagePhase1Seconds: average(of: phase1Seconds),
            averagePhase2Seconds: phase2Seconds.isEmpty ? nil : average(of: phase2Seconds),
            averageTotalWorkflowSeconds: totalWorkflowSeconds.isEmpty ? nil : average(of: totalWorkflowSeconds)
        )
    }

    private static func unorderedItemValueSimilarity(_ lhs: [Phase2Result.Item], _ rhs: [Phase2Result.Item]) -> Double {
        multisetSimilarity(
            lhs.compactMap(\.cents),
            rhs.compactMap(\.cents)
        )
    }

    private static func unorderedLineItemValueSimilarity(_ lhs: [OCRLineItem], _ rhs: [OCRLineItem]) -> Double {
        multisetSimilarity(lhs.map(\.cents), rhs.map(\.cents))
    }

    private static func multisetSimilarity(_ lhs: [Int], _ rhs: [Int]) -> Double {
        if lhs.isEmpty && rhs.isEmpty { return 1.0 }

        let lhsCounts = countsByValue(lhs)
        let rhsCounts = countsByValue(rhs)
        let allKeys = Set(lhsCounts.keys).union(rhsCounts.keys)
        let matched = allKeys.reduce(0) { partial, key in
            partial + min(lhsCounts[key, default: 0], rhsCounts[key, default: 0])
        }
        let denominator = max(lhs.count, rhs.count)
        guard denominator > 0 else { return 1.0 }
        return Double(matched) / Double(denominator)
    }

    private static func countsByValue(_ values: [Int]) -> [Int: Int] {
        var counts: [Int: Int] = [:]
        for value in values {
            counts[value, default: 0] += 1
        }
        return counts
    }

    private static func computedTotal(for snapshot: ReceiptOCRBenchmarkSnapshot) -> Int {
        let itemTotal = snapshot.phase2.items.reduce(0) { partial, item in
            partial + max(0, item.cents ?? 0)
        }
        let lineItemTotal = snapshot.lineItems.reduce(0) { $0 + $1.cents }
        return itemTotal + lineItemTotal
    }

    private static func labelSimilarity(_ lhs: String?, _ rhs: String?) -> Double {
        let left = normalizeLabel(lhs)
        let right = normalizeLabel(rhs)
        if left.isEmpty && right.isEmpty { return 1.0 }
        if left.isEmpty || right.isEmpty { return 0.0 }
        if left == right { return 1.0 }
        let leftTokens = Set(left.split(separator: " ").map(String.init))
        let rightTokens = Set(right.split(separator: " ").map(String.init))
        let union = leftTokens.union(rightTokens).count
        guard union > 0 else { return 0.0 }
        return Double(leftTokens.intersection(rightTokens).count) / Double(union)
    }

    private static func normalizeLabel(_ raw: String?) -> String {
        guard let raw else { return "" }
        let normalized = raw.lowercased().unicodeScalars.map {
            CharacterSet.alphanumerics.contains($0) || CharacterSet.whitespaces.contains($0) ? Character($0) : " "
        }
        return String(normalized)
            .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func numericSimilarity<T: BinaryInteger>(_ lhs: T?, _ rhs: T?) -> Double {
        switch (lhs, rhs) {
        case (nil, nil): return 1.0
        case let (.some(lhs), .some(rhs)): return lhs == rhs ? 1.0 : 0.0
        default: return 0.0
        }
    }

    private static func average(of values: [Double]) -> Double {
        guard !values.isEmpty else { return 0.0 }
        return values.reduce(0, +) / Double(values.count)
    }

    private static func average(weightedValues: [(Double, Double)]) -> Double {
        let totalWeight = weightedValues.reduce(0.0) { $0 + $1.1 }
        guard totalWeight > 0 else { return 0.0 }
        return weightedValues.reduce(0.0) { $0 + ($1.0 * $1.1) } / totalWeight
    }
}
